name: moglow
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - matplotlib
  - numpy
  - pytorch
  - cudatoolkit=10.1
  - scikit-learn
  - tensorboardx
  - tqdm
  - docopt
  - pandas
  - joblib
  - librosa
